### ISSUE TITLE
Some clarifications

### ISSUE THREAD

**Issue by sanjeevmk** [matt-graham/hamiltonian-monte-carlo#1]
Thanks for the library.
I don't understand the math behind HMC, I tried this implementation because its one of the easiest to use.

I have an energy function which can be any Real. And its gradient. For me, samples that have low energy should have higher probability of being sampled. So, I use your implementation with a function that returns e^(-energy) and gradient of e^(-energy). 

Since I don't understand the math here, my first question is, does HMC require that the distribution be normalized (that is, sum of probabilities sum to 1)?
Additionally, I have been facing the following issue. Lets assume a fixed step size. I run the code exactly as in the Readme, but with my energy function and its gradient function.
If I sample N samples, and lets number it sample 1 to sample N, then I find that sample 1 is closer to what I expect, but sample N is much further from it. As I go from 1 to N, I find that I get more violating examples (in terms of my energy). 
Given an initial sample, I expect that all N samples should be independent. But I actually find that sample "m" has higher energy (lower probability thus), than sample "m-1".

Is there a reason for this?

**Comment by matt-graham** [comment]
Hi,

It seems that from you closing this issue that you managed to resolve your problem?

The potential energy function should correspond to the negative logarithm of the (potentially unnormalised) density of the target distribution of interest (in the log domain any normalising constant will be an additive constant which will not affect the simulated Hamiltonian dynamics or density ratio in the acceptance probabilities).

Regards,
Matt
